sudo: required
services:
  - docker

before_install:
  - docker build -t hfuad/react-multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hfuad/react-multi npm test

after_success: 
  - docker build -t hfuad462/multi-client ./client
  - docker build -t hfuad462/multi-nginx ./nginx
  - docker build -t hfuad462/multi-server ./server
  - docker build -t hfuad462/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push hfuad462/multi-client
  - docker push hfuad462/multi-nginx
  - docker push hfuad462/multi-server
  - docker push hfuad462/multi-worker